export { parsePrismaSchema } from './parsers/prismaParser'
export { generateRoutesForModel } from './generators/routeGenerator'
export { generateRouteHandler } from './templates/routeTemplate'
export type { ParsedModel, ParsedSchema } from './parsers/prismaParser'
export type { GeneratorConfig, RouteConfig, GeneratedRoute } from './types'